default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  
development:
  <<: *default
  database: openhousedev
  
test:
  <<: *default
  database: openhousetest